name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip && \
          pip install -r requirements.txt && \
          pip install coverage
      
      - name: Test and save coverage report
        run: |
          coverage run --source='.' manage.py test
          coverage xml -o coverage.xml   
          
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: c39ad9ae42d24b76325fbea626c35fa1d1e8959562e901d7a09241c28deb9789
        with:
          coverageCommand: coverage report
          debug: true
          
